const GRID_SIZE = 30

const SMALL_MAP_PIXELSIZE_WIDTH = 800
const SMALL_MAP_PIXELSIZE_HEIGHT = 600

export type COORD = {
    X: number,
    Y: number
}

export {
    GRID_SIZE,
    SMALL_MAP_PIXELSIZE_WIDTH,
    SMALL_MAP_PIXELSIZE_HEIGHT
}