const GRID_SIZE = 30

const SMALL_MAP_GRIDSIZE_WIDTH = 40
const SMALL_MAP_GRIDSIZE_HEIGHT = 25
const SMALL_MAP_PIXELSIZE_WIDTH = SMALL_MAP_GRIDSIZE_WIDTH * GRID_SIZE
const SMALL_MAP_PIXELSIZE_HEIGHT = SMALL_MAP_GRIDSIZE_HEIGHT * GRID_SIZE


export type COORD = {
    X: number,
    Y: number
}

export {
    GRID_SIZE,
    SMALL_MAP_GRIDSIZE_WIDTH,
    SMALL_MAP_GRIDSIZE_HEIGHT,
    SMALL_MAP_PIXELSIZE_WIDTH,
    SMALL_MAP_PIXELSIZE_HEIGHT
}